export interface Schedule {
    id?: string;
    name?: string;
    userCode?: string;
    mon_Shift1?: string ;
    mon_Shift2?: string ;
    mon_Shift3?: string ;
    mon_Break?: string ;
    tue_Shift1?: string ;
    tue_Shift2?: string ;
    tue_Shift3?: string ;
    tue_Break?: string ;
    wed_Shift1?: string ;
    wed_Shift2?: string ;
    wed_Shift3?: string ;
    wed_Break?: string ;
    thu_Shift1?: string ;
    thu_Shift2?: string ;
    thu_Shift3?: string ;
    thu_Break?: string ;
    fri_Shift1?: string ;
    fri_Shift2?: string ;
    fri_Shift3?: string ;
    fri_Break?: string ;
    sat_Shift1?: string ;
    sat_Shift2?: string ;
    sat_Shift3?: string ;
    sat_Break?: string ;
    sun_Shift1?: string ;
    sun_Shift2?: string ;
    sun_Shift3?: string ;
    sun_Break?: string ;
}
